### ISSUE TITLE
BUG: Constructiong bool constants fails in Z3

### ISSUE THREAD

**Issue by cdonovick** [makaimann/smt-switch#16]
```Python
s = smt('Z3')
x = s.TheoryConst(s.Bool(), True)
```
```
Traceback (most recent call last):
  File ".../smt_switch/src/api.py", line 132, in TheoryConst
    stconst)
  File ".../smt_switch/src/terms.py", line 326, in __init__
    sts = solver_term.sort()
AttributeError: 'bool' object has no attribute 'sort'

**Comment by makaimann** [comment]
Thanks for letting me know! Fixed with 2a4b6c908d80b4852a72d378a29b8573bdf1c6ab.

I also added a test so this kind of thing is caught in the future.
